lcls
lmc
lmhelp
int val0
int val1
cld
function void build_phase (uvm_phase phase);
endfunction

// uvm_driver: TestDriver
// This class generated by snippet: 'driver', if has any issue, pls report to RyanHunter
class TestDriver #(type REQ=uvm_sequence_item,RSP=REQ) extends RhDriverBase#(REQ,RSP);
	RhuDebugger debug; // mostly it comes from agent assignment
	`uvm_component_utils_begin(TestDriver#(REQ,RSP))
	`uvm_component_utils_end
	function new(string name="TestDriver",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	// phases ##{{{
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual function void run_phase(uvm_phase phase);
	// ##}}}
	extern virtual task mainProcess();
endclass
function void TestDriver::build_phase(uvm_phase phase); // ##{{{
	super.build_phase(phase);
	`debug("local build_phase starting ...")
	`debug("local build_phase leaving ...")
	debug.updateChildren(this);
endfunction // ##}}}
function void TestDriver::connect_phase(uvm_phase phase); // ##{{{
	super.connect_phase(phase);
endfunction // ##}}}
task TestDriver::run_phase(uvm_phase phase); // ##{{{
	super.run_phase(phase);
endtask // ##}}}
task TestDriver::mainProcess(); // ##{{{
endtask // ##}}}
//

// uvm_test: Example
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class Example extends uvm_test;
	`uvm_component_utils_begin(Example)
	`uvm_component_utils_end
	function new(string name="Example",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	// phases ##{{{
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	// ##}}}
endclass
function void Example::build_phase(uvm_phase phase); // ##{{{
	super.build_phase(phase);
	//TODO,add code here
endfunction // ##}}}
function void Example::connect_phase(uvm_phase phase); // ##{{{
	super.connect_phase(phase);
endfunction // ##}}}
task Example::run_phase(uvm_phase phase); // ##{{{
	super.run_phase(phase);
endtask // ##}}}

