-- The syntax file, current has only keywords, and will return a table that has keywords
local K={
	'class','module','program','interface',
	'function','forever',
	'always_comb','always_ff','always_latch',
	'class','endclass','new',
	'virtual','local','const','protected',
	'package','endpackage',
	'rand','randc','constraint','randomize',
	'with','inside','dist',
	'sequence','endsequence','randsequence',
	'srandom',
	'logic','bit','byte',
	'int','longint','shortint',
	'struct','packed',
	'final',
	'import','export',
	'context','pure','',
	'void','shortreal','chandle','string',
	'clocking','endclocking','iff',
	'interface','endinterface','modport',
	'cover','covergroup','coverpoint','endgroup',
	'property','endproperty',
	'program','endprogram',
	'bins','binsof','illegal_bins','ignore_bins',
	'alias','matches','solve','static','assert',
	'assume','super','before','expect','bind',
	'extends','null','tagged','extern','this',
	'first_match','throughout','timeprecision',
	'timeunit','type','union','',
	'uwire','var','cross','ref','wait_order','intersect',
	'wildcard','within',
	'typedef','enum',
	'randcase',
	'unique','priority',
	'return','break','continue',
	'do','foreach',
	'join_any','join_none','fork','join',
	'checker','endchecker',
	'accept_on','reject_on',
	'sync_accept_on','sync_reject_on',
	'eventually','nexttime','until','until_with',
	's_always','s_eventually','s_nexttime','s_until','s_until_with',
	'let','untyped',
	'strong','weak',
	'restrict','global','implies',
	'unique0',
	'implements',
	'interconnect','soft','nettype',
};

local syntax={keywords=K};

return syntax;
