// TODO, To copy the prototype part into the class declaration
	extern function bit build_phase (int a);
// This code generated by snippet: 'func', if has any issue, pls report to RyanHunter

function bit TestClass::build_phase(int a); // ##{{{
endfunction // ##}}}
